const { User } = require('../models');

var customPs = '$2a$10$tHu3Q0hQg/hLDgG48IGxk.d0452cKtJGgPtmh05v2MwH.Hi.pslAG';



const userdata = [
  // Start of Male Users List
  {
    id: 1,
    username: 'ken',
    email: 'ken@gmail.com',
    password: customPs,
    firstname: 'Ken',
    lastname: 'H',
    type: 'H',
    gender: 'm',
    interest: 'Baseball, Love Island, Sushi',
    birthday: '644600746765',
    bio: 'Loves bathbombs',
    avatar: 'aaron.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Apple2',
    email: 'apple2@gmail.com',
    password: 'ABC123',
    firstname: 'Adam',
    lastname: 'Smith',
    type: 'H',
    gender: 'm',
    interest: 'Baseball, Love Island, Sushi',
    birthday: '644600746765',
    bio: 'Loves bathbombs',
    avatar: 'adam.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Apple3',
    email: 'apple3@gmail.com',
    password: 'ABC123',
    firstname: 'Alan',
    lastname: 'Smith',
    type: 'H',
    gender: 'm',
    interest: 'Baseball, Love Island, Sushi',
    birthday: '644600746765',
    bio: 'Loves bathbombs',
    avatar: 'alan.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Apple4',
    email: 'apple4@gmail.com',
    password: 'ABC123',
    firstname: 'Alexander',
    lastname: 'Smith',
    type: 'H',
    gender: 'm',
    interest: 'Baseball, Love Island, Sushi',
    birthday: '644600746765',
    bio: 'Loves bathbombs',
    avatar: 'adam.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Apple5',
    email: 'apple5@gmail.com',
    password: 'ABC123',
    firstname: 'Andrew',
    lastname: 'Smith',
    type: 'H',
    gender: 'm',
    interest: 'Baseball, Love Island, Sushi',
    birthday: '644600746765',
    bio: 'Loves bathbombs',
    avatar: 'andrew.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Apple6',
    email: 'apple6@gmail.com',
    password: 'ABC123',
    firstname: 'Andy',
    lastname: 'Smith',
    type: 'H',
    gender: 'm',
    interest: 'Baseball, Love Island, Sushi',
    birthday: '644600746765',
    bio: 'Loves bathbombs',
    avatar: 'andy.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Apple7',
    email: 'apple7@gmail.com',
    password: 'ABC123',
    firstname: 'Anthony',
    lastname: 'Smith',
    type: 'H',
    gender: 'm',
    interest: 'Baseball, Love Island, Sushi',
    birthday: '644600746765',
    bio: 'Loves bathbombs',
    avatar: 'anthony.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Apple8',
    email: 'apple8@gmail.com',
    password: 'ABC123',
    firstname: 'Ben',
    lastname: 'Smith',
    type: 'H',
    gender: 'm',
    interest: 'Baseball, Love Island, Sushi',
    birthday: '644600746765',
    bio: 'Loves bathbombs',
    avatar: 'ben.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Apple9',
    email: 'apple9@gmail.com',
    password: 'ABC123',
    firstname: 'Brandon',
    lastname: 'Smith',
    type: 'H',
    gender: 'm',
    interest: 'Baseball, Love Island, Sushi',
    birthday: '644600746765',
    bio: 'Loves bathbombs',
    avatar: 'brandon.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Apple10',
    email: 'apple10@gmail.com',
    password: 'ABC123',
    firstname: 'Brian',
    lastname: 'Smith',
    type: 'H',
    gender: 'm',
    interest: 'Baseball, Love Island, Sushi',
    birthday: '644600746765',
    bio: 'Loves bathbombs',
    avatar: 'brian.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Banana1',
    email: 'banana1@gmail.com',
    password: 'ABC123',
    firstname: 'Charles',
    lastname: 'Jones',
    type: 'H',
    gender: 'm',
    interest: 'Volleyball, The Office, Pizza',
    birthday: '685382244751',
    bio: 'Loves tropical vacations',
    avatar: 'charles.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Banana2',
    email: 'banana2@gmail.com',
    password: 'ABC123',
    firstname: 'Christopher',
    lastname: 'Jones',
    type: 'H',
    gender: 'm',
    interest: 'Volleyball, The Office, Pizza',
    birthday: '685382244751',
    bio: 'Loves tropical vacations',
    avatar: 'christopher.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Banana3',
    email: 'banana3@gmail.com',
    password: 'ABC123',
    firstname: 'Daniel',
    lastname: 'Jones',
    type: 'H',
    gender: 'm',
    interest: 'Volleyball, The Office, Pizza',
    birthday: '685382244751',
    bio: 'Loves tropical vacations',
    avatar: 'daniel.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Banana4',
    email: 'banana4@gmail.com',
    password: 'ABC123',
    firstname: 'David',
    lastname: 'Jones',
    type: 'H',
    gender: 'm',
    interest: 'Volleyball, The Office, Pizza',
    birthday: '685382244751',
    bio: 'Loves tropical vacations',
    avatar: 'david.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Banana5',
    email: 'banana5@gmail.com',
    password: 'ABC123',
    firstname: 'Dennis',
    lastname: 'Jones',
    type: 'H',
    gender: 'm',
    interest: 'Volleyball, The Office, Pizza',
    birthday: '685382244751',
    bio: 'Loves tropical vacations',
    avatar: 'dennis.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Banana6',
    email: 'banana6@gmail.com',
    password: 'ABC123',
    firstname: 'Donald',
    lastname: 'Jones',
    type: 'H',
    gender: 'm',
    interest: 'Volleyball, The Office, Pizza',
    birthday: '685382244751',
    bio: 'Loves tropical vacations',
    avatar: 'donald.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Banana7',
    email: 'banana7@gmail.com',
    password: 'ABC123',
    firstname: 'Douglas',
    lastname: 'Jones',
    type: 'H',
    gender: 'm',
    interest: 'Volleyball, The Office, Pizza',
    birthday: '685382244751',
    bio: 'Loves tropical vacations',
    avatar: 'douglas.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Banana8',
    email: 'banana8@gmail.com',
    password: 'ABC123',
    firstname: 'Duncan',
    lastname: 'Jones',
    type: 'H',
    gender: 'm',
    interest: 'Volleyball, The Office, Pizza',
    birthday: '685382244751',
    bio: 'Loves tropical vacations',
    avatar: 'duncan.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Banana9',
    email: 'banana9@gmail.com',
    password: 'ABC123',
    firstname: 'Dylan',
    lastname: 'Jones',
    type: 'H',
    gender: 'm',
    interest: 'Volleyball, The Office, Pizza',
    birthday: '685382244751',
    bio: 'Loves tropical vacations',
    avatar: 'dylan.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Banana10',
    email: 'banana10@gmail.com',
    password: 'ABC123',
    firstname: 'Edward',
    lastname: 'Jones',
    type: 'H',
    gender: 'm',
    interest: 'Volleyball, The Office, Pizza',
    birthday: '685382244751',
    bio: 'Loves tropical vacations',
    avatar: 'edward.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Cherry1',
    email: 'cherry1@gmail.com',
    password: 'ABC123',
    firstname: 'Eric',
    lastname: 'Lee',
    type: 'H',
    gender: 'm',
    interest: 'League of Legends, South Park, Chicken Nuggets',
    birthday: '890847842993',
    bio: 'Loves podcasts',
    avatar: 'eric.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Cherry2',
    email: 'cherry2@gmail.com',
    password: 'ABC123',
    firstname: 'Gary',
    lastname: 'Lee',
    type: 'H',
    gender: 'm',
    interest: 'League of Legends, South Park, Chicken Nuggets',
    birthday: '890847842993',
    bio: 'Loves podcasts',
    avatar: 'gary.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Cherry3',
    email: 'cherry3@gmail.com',
    password: 'ABC123',
    firstname: 'George',
    lastname: 'Lee',
    type: 'H',
    gender: 'm',
    interest: 'League of Legends, South Park, Chicken Nuggets',
    birthday: '890847842993',
    bio: 'Loves podcasts',
    avatar: 'george.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Cherry4',
    email: 'cherry4@gmail.com',
    password: 'ABC123',
    firstname: 'Gregory',
    lastname: 'Lee',
    type: 'H',
    gender: 'm',
    interest: 'League of Legends, South Park, Chicken Nuggets',
    birthday: '890847842993',
    bio: 'Loves podcasts',
    avatar: 'gregory.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Cherry5',
    email: 'cherry5@gmail.com',
    password: 'ABC123',
    firstname: 'Jack',
    lastname: 'Lee',
    type: 'H',
    gender: 'm',
    interest: 'League of Legends, South Park, Chicken Nuggets',
    birthday: '890847842993',
    bio: 'Loves podcasts',
    avatar: 'jack.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Cherry6',
    email: 'cherry6@gmail.com',
    password: 'ABC123',
    firstname: 'Jacob',
    lastname: 'Lee',
    type: 'H',
    gender: 'm',
    interest: 'League of Legends, South Park, Chicken Nuggets',
    birthday: '890847842993',
    bio: 'Loves podcasts',
    avatar: 'jacob.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Cherry7',
    email: 'cherry7@gmail.com',
    password: 'ABC123',
    firstname: 'James',
    lastname: 'Lee',
    type: 'H',
    gender: 'm',
    interest: 'League of Legends, South Park, Chicken Nuggets',
    birthday: '890847842993',
    bio: 'Loves podcasts',
    avatar: 'jacob.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Cherry8',
    email: 'cherry8@gmail.com',
    password: 'ABC123',
    firstname: 'Jason',
    lastname: 'Lee',
    type: 'H',
    gender: 'm',
    interest: 'League of Legends, South Park, Chicken Nuggets',
    birthday: '890847842993',
    bio: 'Loves podcasts',
    avatar: 'jason.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Cherry9',
    email: 'cherry9@gmail.com',
    password: 'ABC123',
    firstname: 'Jeff',
    lastname: 'Lee',
    type: 'H',
    gender: 'm',
    interest: 'League of Legends, South Park, Chicken Nuggets',
    birthday: '890847842993',
    bio: 'Loves podcasts',
    avatar: 'jeff.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Cherry10',
    email: 'cherry10@gmail.com',
    password: 'ABC123',
    firstname: 'Jerry',
    lastname: 'Lee',
    type: 'H',
    gender: 'm',
    interest: 'League of Legends, South Park, Chicken Nuggets',
    birthday: '890847842993',
    bio: 'Loves podcasts',
    avatar: 'jerry.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Dessert1',
    email: 'dessert1@gmail.com',
    password: 'ABC123',
    firstname: 'John',
    lastname: 'Paul',
    type: 'H',
    gender: 'm',
    interest: 'Billiards, Sopranos, Subway',
    birthday: '890847842993',
    bio: 'Enjoys camping, fishing and the outdoors',
    avatar: 'john.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Dessert2',
    email: 'dessert2@gmail.com',
    password: 'ABC123',
    firstname: 'Joseph',
    lastname: 'Paul',
    type: 'H',
    gender: 'm',
    interest: 'Billiards, Sopranos, Subway',
    birthday: '890847842993',
    bio: 'Enjoys camping, fishing and the outdoors',
    avatar: 'joseph.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Dessert3',
    email: 'dessert3@gmail.com',
    password: 'ABC123',
    firstname: 'Joshua',
    lastname: 'Paul',
    type: 'H',
    gender: 'm',
    interest: 'Billiards, Sopranos, Subway',
    birthday: '890847842993',
    bio: 'Enjoys camping, fishing and the outdoors',
    avatar: 'joshua.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Dessert4',
    email: 'dessert4@gmail.com',
    password: 'ABC123',
    firstname: 'Justin',
    lastname: 'Paul',
    type: 'H',
    gender: 'm',
    interest: 'Billiards, Sopranos, Subway',
    birthday: '890847842993',
    bio: 'Enjoys camping, fishing and the outdoors',
    avatar: 'justin.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Dessert5',
    email: 'dessert5@gmail.com',
    password: 'ABC123',
    firstname: 'Keith',
    lastname: 'Paul',
    type: 'H',
    gender: 'm',
    interest: 'Billiards, Sopranos, Subway',
    birthday: '890847842993',
    bio: 'Enjoys camping, fishing and the outdoors',
    avatar: 'keith.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Dessert6',
    email: 'dessert6@gmail.com',
    password: 'ABC123',
    firstname: 'Kenneth',
    lastname: 'Paul',
    type: 'H',
    gender: 'm',
    interest: 'Billiards, Sopranos, Subway',
    birthday: '890847842993',
    bio: 'Enjoys camping, fishing and the outdoors',
    avatar: 'kenneth.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Dessert7',
    email: 'dessert7@gmail.com',
    password: 'ABC123',
    firstname: 'Kevin',
    lastname: 'Paul',
    type: 'H',
    gender: 'm',
    interest: 'Billiards, Sopranos, Subway',
    birthday: '890847842993',
    bio: 'Enjoys camping, fishing and the outdoors',
    avatar: 'kevin.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Dessert8',
    email: 'dessert8@gmail.com',
    password: 'ABC123',
    firstname: 'Kyle',
    lastname: 'Paul',
    type: 'H',
    gender: 'm',
    interest: 'Billiards, Sopranos, Subway',
    birthday: '890847842993',
    bio: 'Enjoys camping, fishing and the outdoors',
    avatar: 'kyle.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Dessert9',
    email: 'dessert9@gmail.com',
    password: 'ABC123',
    firstname: 'Larry',
    lastname: 'Paul',
    type: 'H',
    gender: 'm',
    interest: 'Billiards, Sopranos, Subway',
    birthday: '890847842993',
    bio: 'Enjoys camping, fishing and the outdoors',
    avatar: 'larry.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Dessert10',
    email: 'dessert10@gmail.com',
    password: 'ABC123',
    firstname: 'Logan',
    lastname: 'Paul',
    type: 'H',
    gender: 'm',
    interest: 'Billiards, Sopranos, Subway',
    birthday: '890847842993',
    bio: 'Enjoys camping, fishing and the outdoors',
    avatar: 'logan.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Entree1',
    email: 'entree1@gmail.com',
    password: 'ABC123',
    firstname: 'Mark',
    lastname: 'Andrews',
    type: 'H',
    gender: 'm',
    interest: 'Football, Nicholas Sparks, Pasta',
    birthday: '509739790066',
    bio: 'I hate smartphones, so I use a pager',
    avatar: 'mark.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Entree2',
    email: 'entree2@gmail.com',
    password: 'ABC123',
    firstname: 'Matthew',
    lastname: 'Andrews',
    type: 'H',
    gender: 'm',
    interest: 'Football, Nicholas Sparks, Pasta',
    birthday: '509739790066',
    bio: 'I hate smartphones, so I use a pager',
    avatar: 'matthew.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Entree3',
    email: 'entree3@gmail.com',
    password: 'ABC123',
    firstname: 'Michael',
    lastname: 'Scott',
    type: 'H',
    gender: 'm',
    interest: 'Football, Nicholas Sparks, Pasta',
    birthday: '509739790066',
    bio: 'I hate smartphones, so I use a pager',
    avatar: 'michael.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Entree4',
    email: 'entree4@gmail.com',
    password: 'ABC123',
    firstname: 'Nicholas',
    lastname: 'Andrews',
    type: 'H',
    gender: 'm',
    interest: 'Football, Nicholas Sparks, Pasta',
    birthday: '509739790066',
    bio: 'I hate smartphones, so I use a pager',
    avatar: 'nicholas.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Entree5',
    email: 'entree5@gmail.com',
    password: 'ABC123',
    firstname: 'Noah',
    lastname: 'Andrews',
    type: 'H',
    gender: 'm',
    interest: 'Football, Nicholas Sparks, Pasta',
    birthday: '509739790066',
    bio: 'I hate smartphones, so I use a pager',
    avatar: 'noah.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Entree6',
    email: 'entree6@gmail.com',
    password: 'ABC123',
    firstname: 'Patrick',
    lastname: 'Andrews',
    type: 'H',
    gender: 'm',
    interest: 'Football, Nicholas Sparks, Pasta',
    birthday: '509739790066',
    bio: 'I hate smartphones, so I use a pager',
    avatar: 'patrick.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Entree7',
    email: 'entree7@gmail.com',
    password: 'ABC123',
    firstname: 'Paul',
    lastname: 'Andrews',
    type: 'H',
    gender: 'm',
    interest: 'Football, Nicholas Sparks, Pasta',
    birthday: '509739790066',
    bio: 'I hate smartphones, so I use a pager',
    avatar: 'paul.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Entree8',
    email: 'entree8@gmail.com',
    password: 'ABC123',
    firstname: 'Peter',
    lastname: 'Andrews',
    type: 'H',
    gender: 'm',
    interest: 'Football, Nicholas Sparks, Pasta',
    birthday: '509739790066',
    bio: 'I hate smartphones, so I use a pager',
    avatar: 'peter.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Entree9',
    email: 'entree9@gmail.com',
    password: 'ABC123',
    firstname: 'Raymond',
    lastname: 'Andrews',
    type: 'H',
    gender: 'm',
    interest: 'Football, Nicholas Sparks, Pasta',
    birthday: '509739790066',
    bio: 'I hate smartphones, so I use a pager',
    avatar: 'raymond.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Entree10',
    email: 'entree10@gmail.com',
    password: 'ABC123',
    firstname: 'Richard',
    lastname: 'Andrews',
    type: 'H',
    gender: 'm',
    interest: 'Football, Nicholas Sparks, Pasta',
    birthday: '509739790066',
    bio: 'I hate smartphones, so I use a pager',
    avatar: 'richard.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Fries1',
    email: 'fries1@gmail.com',
    password: 'ABC123',
    firstname: 'Robert',
    lastname: 'Scott',
    type: 'H',
    gender: 'm',
    interest: 'Metallica, Taylor Swift, French Fries',
    birthday: '568924499186',
    bio: 'I have a forklift license',
    avatar: 'robert.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Fries2',
    email: 'fries2@gmail.com',
    password: 'ABC123',
    firstname: 'Ryan',
    lastname: 'Scott',
    type: 'H',
    gender: 'm',
    interest: 'Metallica, Taylor Swift, French Fries',
    birthday: '568924499186',
    bio: 'I have a forklift license',
    avatar: 'ryan.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Fries3',
    email: 'fries3@gmail.com',
    password: 'ABC123',
    firstname: 'Samuel',
    lastname: 'Scott',
    type: 'H',
    gender: 'm',
    interest: 'Metallica, Taylor Swift, French Fries',
    birthday: '568924499186',
    bio: 'I have a forklift license',
    avatar: 'samuel.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Fries4',
    email: 'fries4@gmail.com',
    password: 'ABC123',
    firstname: 'Scott',
    lastname: 'Andrews',
    type: 'H',
    gender: 'm',
    interest: 'Metallica, Taylor Swift, French Fries',
    birthday: '568924499186',
    bio: 'I have a forklift license',
    avatar: 'scott.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Fries5',
    email: 'fries5@gmail.com',
    password: 'ABC123',
    firstname: 'Thomas',
    lastname: 'Scott',
    type: 'H',
    gender: 'm',
    interest: 'Metallica, Taylor Swift, French Fries',
    birthday: '568924499186',
    bio: 'I have a forklift license',
    avatar: 'thomas.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Fries6',
    email: 'fries6@gmail.com',
    password: 'ABC123',
    firstname: 'Tim',
    lastname: 'Scott',
    type: 'H',
    gender: 'm',
    interest: 'Metallica, Taylor Swift, French Fries',
    birthday: '568924499186',
    bio: 'I have a forklift license',
    avatar: 'tim.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Fries7',
    email: 'fries7@gmail.com',
    password: 'ABC123',
    firstname: 'Tyler',
    lastname: 'Scott',
    type: 'H',
    gender: 'm',
    interest: 'Metallica, Taylor Swift, French Fries',
    birthday: '568924499186',
    bio: 'I have a forklift license',
    avatar: 'tyler.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Fries8',
    email: 'fries8@gmail.com',
    password: 'ABC123',
    firstname: 'Wayne',
    lastname: 'Scott',
    type: 'H',
    gender: 'm',
    interest: 'Metallica, Taylor Swift, French Fries',
    birthday: '568924499186',
    bio: 'I have a forklift license',
    avatar: 'wayne.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Fries9',
    email: 'fries9@gmail.com',
    password: 'ABC123',
    firstname: 'William',
    lastname: 'Scott',
    type: 'H',
    gender: 'm',
    interest: 'Metallica, Taylor Swift, French Fries',
    birthday: '568924499186',
    bio: 'I have a forklift license',
    avatar: 'william.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Fries10',
    email: 'fries10@gmail.com',
    password: 'ABC123',
    firstname: 'Wing',
    lastname: 'Scott',
    type: 'H',
    gender: 'm',
    interest: 'Metallica, Taylor Swift, French Fries',
    birthday: '568924499186',
    bio: 'I have a forklift license',
    avatar: 'wing.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },

  // Start of Female Users List

  {
    id: 61,
    username: 'Guac1',
    email: 'guac1@gmail.com',
    password: customPs,
    firstname: 'Alice',
    lastname: 'Chan',
    type: 'H',
    gender: 'f',
    interest: 'Painting, Billie Eilish, Mimosas',
    birthday: '847392294371',
    bio: 'I\'m a Michelin-star chef',
    avatar: 'alice.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    id: 62,
    username: 'amandalovecola',
    email: 'amada@gmail.com',
    password: customPs,
    firstname: 'Amanda',
    lastname: 'Chan',
    type: 'A',
    gender: 'f',
    interest: 'Painting, Billie Eilish, Mimosas',
    birthday: '847392294371',
    bio: 'I\'m a Michelin-star chef',
    avatar: 'amanda.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },{
    username: 'Guac3',
    email: 'guac3@gmail.com',
    password: 'ABC123',
    firstname: 'Amy',
    lastname: 'Chan',
    type: 'H',
    gender: 'f',
    interest: 'Painting, Billie Eilish, Mimosas',
    birthday: '847392294371',
    bio: 'I\'m a Michelin-star chef',
    avatar: 'amy.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Guac4',
    email: 'guac4@gmail.com',
    password: 'ABC123',
    firstname: 'Angela',
    lastname: 'Chan',
    type: 'H',
    gender: 'f',
    interest: 'Painting, Billie Eilish, Mimosas',
    birthday: '847392294371',
    bio: 'I\'m a Michelin-star chef',
    avatar: 'angela.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Guac5',
    email: 'guac5@gmail.com',
    password: 'ABC123',
    firstname: 'Anna',
    lastname: 'Chan',
    type: 'H',
    gender: 'f',
    interest: 'Painting, Billie Eilish, Mimosas',
    birthday: '847392294371',
    bio: 'I\'m a Michelin-star chef',
    avatar: 'anna.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Guac6',
    email: 'guac6@gmail.com',
    password: 'ABC123',
    firstname: 'Ashley',
    lastname: 'Chan',
    type: 'H',
    gender: 'f',
    interest: 'Painting, Billie Eilish, Mimosas',
    birthday: '847392294371',
    bio: 'I\'m a Michelin-star chef',
    avatar: 'ashley.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Guac7',
    email: 'guac7@gmail.com',
    password: 'ABC123',
    firstname: 'Barbara',
    lastname: 'Chan',
    type: 'H',
    gender: 'f',
    interest: 'Painting, Billie Eilish, Mimosas',
    birthday: '847392294371',
    bio: 'I\'m a Michelin-star chef',
    avatar: 'barbara.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Guac8',
    email: 'guac8@gmail.com',
    password: 'ABC123',
    firstname: 'Betty',
    lastname: 'Chan',
    type: 'H',
    gender: 'f',
    interest: 'Painting, Billie Eilish, Mimosas',
    birthday: '847392294371',
    bio: 'I\'m a Michelin-star chef',
    avatar: 'betty.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Guac9',
    email: 'guac9@gmail.com',
    password: 'ABC123',
    firstname: 'Brenda',
    lastname: 'Chan',
    type: 'H',
    gender: 'f',
    interest: 'Painting, Billie Eilish, Mimosas',
    birthday: '847392294371',
    bio: 'I\'m a Michelin-star chef',
    avatar: 'brenda.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Guac10',
    email: 'guac10@gmail.com',
    password: 'ABC123',
    firstname: 'Christina',
    lastname: 'Chan',
    type: 'H',
    gender: 'f',
    interest: 'Painting, Billie Eilish, Mimosas',
    birthday: '847392294371',
    bio: 'I\'m a Michelin-star chef',
    avatar: 'christina.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Habanero1',
    email: 'habanero1@gmail.com',
    password: 'ABC123',
    firstname: 'Claire',
    lastname: 'Stone',
    type: 'H',
    gender: 'f',
    interest: 'Basketball, Red Hot Chilli Peppers, Noodles',
    birthday: '728939303988',
    bio: 'I worship Martha Stewart',
    avatar: 'claire.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Habanero2',
    email: 'habanero2@gmail.com',
    password: 'ABC123',
    firstname: 'Cynthia',
    lastname: 'Stone',
    type: 'H',
    gender: 'f',
    interest: 'Basketball, Red Hot Chilli Peppers, Noodles',
    birthday: '728939303988',
    bio: 'I worship Martha Stewart',
    avatar: 'cynthia.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Habanero3',
    email: 'habanero3@gmail.com',
    password: 'ABC123',
    firstname: 'Deborah',
    lastname: 'Stone',
    type: 'H',
    gender: 'f',
    interest: 'Basketball, Red Hot Chilli Peppers, Noodles',
    birthday: '728939303988',
    bio: 'I worship Martha Stewart',
    avatar: 'deborah.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Habanero4',
    email: 'habanero4@gmail.com',
    password: 'ABC123',
    firstname: 'Debra',
    lastname: 'Stone',
    type: 'H',
    gender: 'f',
    interest: 'Basketball, Red Hot Chilli Peppers, Noodles',
    birthday: '728939303988',
    bio: 'I worship Martha Stewart',
    avatar: 'debra.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Habanero5',
    email: 'habanero5@gmail.com',
    password: 'ABC123',
    firstname: 'Diane',
    lastname: 'Stone',
    type: 'H',
    gender: 'f',
    interest: 'Basketball, Red Hot Chilli Peppers, Noodles',
    birthday: '728939303988',
    bio: 'I worship Martha Stewart',
    avatar: 'diane.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Habanero6',
    email: 'habanero6@gmail.com',
    password: 'ABC123',
    firstname: 'Donna',
    lastname: 'Stone',
    type: 'H',
    gender: 'f',
    interest: 'Basketball, Red Hot Chilli Peppers, Noodles',
    birthday: '728939303988',
    bio: 'I\'m a legal secretary of the top law firm in New York City.',
    avatar: 'donna.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Habanero7',
    email: 'habanero7@gmail.com',
    password: 'ABC123',
    firstname: 'Dorothy',
    lastname: 'Stone',
    type: 'H',
    gender: 'f',
    interest: 'Basketball, Red Hot Chilli Peppers, Noodles',
    birthday: '728939303988',
    bio: 'I worship Martha Stewart',
    avatar: 'dorothy.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Habanero8',
    email: 'habanero8@gmail.com',
    password: 'ABC123',
    firstname: 'Elizabeth',
    lastname: 'Stone',
    type: 'H',
    gender: 'f',
    interest: 'Basketball, Red Hot Chilli Peppers, Noodles',
    birthday: '728939303988',
    bio: 'I worship Martha Stewart',
    avatar: 'elizabeth.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Habanero9',
    email: 'habanero9@gmail.com',
    password: 'ABC123',
    firstname: 'Emily',
    lastname: 'Stone',
    type: 'H',
    gender: 'f',
    interest: 'Basketball, Red Hot Chilli Peppers, Noodles',
    birthday: '728939303988',
    bio: 'I worship Martha Stewart',
    avatar: 'emily.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'Habanero10',
    email: 'habanero10@gmail.com',
    password: 'ABC123',
    firstname: 'Emma',
    lastname: 'Stone',
    type: 'H',
    gender: 'f',
    interest: 'Basketball, Red Hot Chilli Peppers, Noodles',
    birthday: '728939303988',
    bio: 'I starred in Ha Ha Land (No it\'s not the same as La La Land)',
    avatar: 'emma.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
  {
    username: 'IceTea1',
    email: 'icetea1@gmail.com',
    password: 'ABC123',
    firstname: 'Evelyn',
    lastname: 'S',
    type: 'H',
    gender: 'f',
    interest: 'Basketball, Red Hot Chilli Peppers, Noodles',
    birthday: '728939303988',
    bio: 'I worship Martha Stewart',
    avatar: 'deborah.jpg',
    created_time: Date.now(),
    updated_time: Date.now(),
  },
];

const seedUsers = () => User.bulkCreate(userdata);

module.exports = seedUsers;
